"""
Analysis of tokenization format vs generation code
"""

print("=== TOKENIZATION FORMAT (from tokenize-asap.py + alignment.py) ===\n")

print("matched_tuples structure:")
print("  t[0] = performance tokens WITH CONTROL_OFFSET already added")
print("  t[1] = performance index") 
print("  t[2] = score tokens (no offset)")
print("  t[3] = score index")
print()

print("Tokenization builds:")
print("1. PREFIX (first k=33 matched tuples):")
print("   for t in matched_tuples[:33]:")
print("     cc = t[0]  # performance with CONTROL_OFFSET")
print("     add cc")
print("     add [TIME_OFFSET + (cc[0]-CONTROL_OFFSET), DUR_OFFSET+0, REST]")
print()
print("   Result: [perf_ctrl, rest, perf_ctrl, rest, ...] x 33")
print()

print("2. ALTERNATING (all matched tuples):")
print("   for i, t in enumerate(matched_tuples):")
print("     sc = t[2]  # SCORE tokens")
print("     add sc")
print("     if i+k < len(matched_tuples):")
print("       add matched_tuples[i+k][0]  # FUTURE PERFORMANCE with CONTROL_OFFSET")
print()
print("   Result: [score, future_perf_ctrl, score, future_perf_ctrl, ...]")
print()

print("3. PREPEND: [SEP, SEP, SEP]")
print("4. INSERT at position 0: ANTICIPATE")
print()

print("FINAL FORMAT:")
print("  [ANTICIPATE, SEP, SEP, SEP, ")
print("   perf_ctrl_0, rest_0, perf_ctrl_1, rest_1, ..., perf_ctrl_32, rest_32,  # PREFIX")
print("   score_0, perf_ctrl_33, score_1, perf_ctrl_34, ...]  # ALTERNATING")
print()
print("="*70)
print()

print("=== WHAT WE EXTRACT IN test.py ===\n")

print("From test data, we extract 'controls' which should be:")
print("  - First 33 performance tokens from prefix (already have CONTROL_OFFSET)")
print("  - Future performance tokens from alternating section (already have CONTROL_OFFSET)")
print()

print("Current extraction code:")
print("  1. Extract prefix: control_triplet (which is performance with CONTROL_OFFSET) ✓")
print("  2. Extract alternating: future_score + add CONTROL_OFFSET ✗ WRONG!")
print()
print("The alternating section already has performance tokens with CONTROL_OFFSET!")
print("We should NOT add CONTROL_OFFSET again!")
print()
print("="*70)
print()

print("=== WHAT generate4 EXPECTS ===\n")

print("generate4(model, controls, ...):")
print("  Expects 'controls' to be performance tokens with CONTROL_OFFSET")
print("  ")
print("  It builds:")
print("    PREFIX: for each control in controls[:33]:")
print("      - Add control triplet")
print("      - Add rest triplet [TIME, DUR=0, REST]")
print("  ")
print("    ALTERNATING: for each generation step i:")
print("      - Generate score triplet")
print("      - Add controls[33+i] if available")
print()
print("This matches the training format! ✓")
print()
print("="*70)
print()

print("CONCLUSION:")
print("  ✗ test.py extraction is WRONG - adding CONTROL_OFFSET to already-offset tokens")
print("  ✓ generate4 is CORRECT - expecting controls with CONTROL_OFFSET")
print("  ")
print("FIX: In test.py, extract tokens as-is without adding CONTROL_OFFSET")
