_wandb:
    value:
        cli_version: 0.27.2
        e:
            zui4bthjdq4uv3vq5r13p04ner950zdy:
                args:
                    - --data_file
                    - data/train_normalized.txt
                    - --val_file
                    - data/test_normalized.txt
                    - --output_dir
                    - ./run_nodummy
                    - --wandb_run_name
                    - run_nodummy
                    - --wandb_mode
                    - online
                    - --max_steps
                    - "20000"
                codePath: train.py
                codePathLocal: train.py
                cpu_count: 56
                cpu_count_logical: 56
                cudaVersion: "12.8"
                disk:
                    /:
                        total: "85832237056"
                        used: "38892277760"
                email: wjl86@cornell.edu
                executable: /home/wjl86/miniconda3/bin/python
                git:
                    commit: 533bf00aa9c8e438a26c377bafb3b4cddf3c1bcf
                    remote: https://github.com/william590y/anticipation3.git
                gpu: NVIDIA GeForce RTX 3090
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Ampere
                      cudaCores: 10496
                      memoryTotal: "25769803776"
                      name: NVIDIA GeForce RTX 3090
                      uuid: GPU-87eb9131-141b-d542-d6f9-1457a2a7b348
                host: ellis-compute-01.cs.cornell.edu
                memory:
                    total: "270095765504"
                os: Linux-6.8.0-124-generic-x86_64-with-glibc2.39
                program: /home/wjl86/anticipation3/train.py
                python: CPython 3.13.5
                root: run_nodummy
                slurm:
                    cluster_name: unicorn
                    conf: /var/spool/slurmd/conf-cache/slurm.conf
                    cpus_on_node: "4"
                    cpus_per_task: "4"
                    gpus: "1"
                    gpus_on_node: "1"
                    gtids: "0"
                    job_account: thickstun
                    job_cpus_per_node: "4"
                    job_end_time: "1814753996"
                    job_gid: "1723234"
                    job_gpus: "0"
                    job_id: "741609"
                    job_name: train-asap
                    job_nodelist: ellis-compute-01
                    job_num_nodes: "1"
                    job_partition: ellis
                    job_qos: normal
                    job_start_time: "1783217996"
                    job_uid: "1685572"
                    job_user: wjl86
                    jobid: "741609"
                    localid: "0"
                    mem_per_node: "16384"
                    nnodes: "1"
                    nodeid: "0"
                    nodelist: ellis-compute-01
                    nprocs: "1"
                    ntasks: "1"
                    oom_kill_step: "0"
                    prio_process: "0"
                    procid: "0"
                    submit_dir: /home/wjl86/anticipation3
                    submit_host: unicorn-login-02
                    task_pid: "1999775"
                    tasks_per_node: "1"
                    topology_addr: ellis-compute-01
                    topology_addr_pattern: node
                    tres_per_task: cpu=4
                startedAt: "2026-07-05T02:20:13.370387Z"
                writerId: zui4bthjdq4uv3vq5r13p04ner950zdy
        m: []
        python_version: 3.13.5
        t:
            "1":
                - 1
                - 5
                - 11
                - 49
                - 53
                - 71
            "2":
                - 1
                - 5
                - 6
                - 11
                - 41
                - 49
                - 53
                - 71
            "3":
                - 2
                - 13
                - 16
            "4": 3.13.5
            "5": 0.27.2
            "6": 4.56.2
            "12": 0.27.2
            "13": linux-x86_64
batch_size:
    value: 8
data_file:
    value: data/train_normalized.txt
disable_autoregressive_pitch_eval:
    value: false
dur_jitter_range:
    value: 0.05
eval_autoregressive_samples:
    value: 100
eval_max_samples:
    value: 500
eval_num_workers:
    value: 0
eval_steps:
    value: 1000
force_cpu:
    value: false
gradient_accumulation_steps:
    value: 4
learning_rate:
    value: 3e-05
loss_mask_performance_tokens:
    value: false
mask_prob:
    value: 0
max_steps:
    value: 20000
model_name:
    value: stanford-crfm/music-medium-800k
onset_jitter_std:
    value: 0.05
original_weight_l2:
    value: 100000
output_dir:
    value: run_nodummy
reduce_memory:
    value: false
save_steps:
    value: 2500
tempo_scale_range:
    value: 0.2
transpose_range_semitones:
    value: 12
val_batch_size:
    value: 8
val_file:
    value: data/test_normalized.txt
wandb_mode:
    value: online
wandb_project:
    value: anticipation-asap
wandb_run_name:
    value: run_nodummy
warmup_steps:
    value: 0
